In [1]:
import pandas as pd

In [10]:
from google.colab import files
uploaded = files.upload()

Saving StudentsPerformance.csv to StudentsPerformance.csv

In [11]:
df = pd.read_csv("StudentsPerformance.csv")

In [12]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [18]:
df["Average"] = df[["math score", "reading score", "writing score"]].mean(axis=1)

In [19]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Average
0,female,group B,bachelor's degree,standard,none,72,72,74,72.666667
1,female,group C,some college,standard,completed,69,90,88,82.333333
2,female,group B,master's degree,standard,none,90,95,93,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.333333
4,male,group C,some college,standard,none,76,78,75,76.333333

In [20]:
df["Average"].max()

100.0

In [21]:
df["Average"].min()

9.0

In [28]:
df.loc[df["Average"] >= 90, "Grade"] = "A"
df.loc[(df["Average"] >= 75) & (df["Average"] < 90), "Grade"] = "B"
df.loc[(df["Average"] >= 65) & (df["Average"] < 75), "Grade"] = "C"
df.loc[(df["Average"] >= 55) & (df["Average"] < 65), "Grade"] = "D"
df.loc[df["Average"] < 55, "Grade"] = "F"

In [29]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Average,Grade
0,female,group B,bachelor's degree,standard,none,72,72,74,72.666667,C
1,female,group C,some college,standard,completed,69,90,88,82.333333,B
2,female,group B,master's degree,standard,none,90,95,93,92.666667,A
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.333333,F
4,male,group C,some college,standard,none,76,78,75,76.333333,B

In [31]:
from google.colab import files

df.to_csv("final_dataset.csv", index=False)
files.download("final_dataset.csv")